[package]
name = "gui"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
toml.workspace = true
anyhow.workspace = true
rand.workspace = true
serde_yaml.workspace = true
serde_json.workspace = true
commonwl = { path = "../cwl" }
s4n_core = { path = "../core" }
repository = { path = "../repository" }
dioxus = { version = "0.7.1", features = ["router"] }
dioxus-free-icons = { version = "0.10.0", features = ["octicons"] }
dioxus-primitives = { git = "https://github.com/DioxusLabs/components", version = "0.0.1", default-features = false }
petgraph = "0.8.3"
rust-sugiyama = "0.4.0"
rfd = { version = "0.15.4", default-features = false, features = [
    "tokio",
    "xdg-portal",
] }
ignore = "0.4.23"

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
