[application]
name = "SciWIn Studio"
default_platform = "desktop"
asset_dir = "assets"

[bundle]
identifier = "net.fairagro.sciwin.studio"
publisher = "FAIRagro"
icon = ["assets/icon.ico", "assets/icon.png"]
resources = ["/assets/**/*"]
category = "Productivity"

[bundle.windows]
icon_path = "packages/gui/assets/icon.ico"

[web.app]
title = "SciWIn Studio"

[web.resource]
style = ["assets/main.css", "assets/tailwind.css"]
script = []

[web.resource.dev]
script = []
