[application]
name = "SciWIn Studio"
default_platform = "desktop"

[bundle]
identifier = "net.fairagro.sciwin.studio"
publisher = "FAIRagro"
icon = ["assets/icon.ico"]

[web.app]
title = "SciWIn Studio"

[web.resource]
style = ["assets/main.css", "assets/tailwind.css"]
script = []

[web.resource.dev]
script = []
