[package]
name = "s4n_core"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
commonwl = { path = "../cwl", features = ["execution", "annotation"] }
repository = { path = "../repository" }
util = { path = "../util" }

anyhow.workspace = true
pathdiff.workspace = true
rand.workspace = true
serde.workspace = true
serde_yaml.workspace = true
tempfile = { workspace = true }
toml.workspace = true
toml_edit.workspace = true

semver = { version = "1.0.26", features = ["serde"] }
shlex = "1.3.0"
slugify = "0.1.0"
smart-default = "0.7.1"

[dev-dependencies]
calamine = "0.31.0"

test_utils = { workspace = true }
rstest = { workspace = true }
serial_test = { workspace = true }

[lints]
workspace = true
