[package]
name = "cwl"
version = "0.1.0"
description = "CWL Rust library, intended to be used for YAML parsing with serde"
edition = "2021"
readme = "../README.md"
repository = "https://github.com/fairagro/m4.4_sciwin_client"
license = "MIT or Apache-2.0"
authors = [
    "Jens Krumsieck",
    "Antonia Leidel",
    "Harald von Waldow",
    "Patrick KÃ¶nig",
]
keywords = [
    "cwl",
    "common workflow language",
    "commonwl",
    "workflow",
    "fairagro",
]
categories = ["science"]

[dependencies]
serde = { workspace = true }
serde_yaml = { workspace = true }
sha1 = "0.10.6"

[dev-dependencies]
rstest = "0.25.0"
