[package]
name = "reana"
description = "Contains REANA related code"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
commonwl = { path = "../cwl" }
util = { path = "../util" }
anyhow = { workspace = true }
fancy-regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tempfile = { workspace = true }
pathdiff = { workspace = true }
toml_edit = { workspace = true }
keyring = { workspace = true }
uuid = { workspace = true }

chrono = { version = "0.4.41" }

[dev-dependencies]
mockito = "1.7.1"
httpmock = "0.8.2"
